[default]
    [default.path]
    raw_data = "/media/yacine/Intenso/RawData"
    processed_data = "/home/yacine/Documents/PhD/Code/GitProject/OOD/data"
    project = "/home/yacine/Documents/PhD/Code/GitProject/OOD"
